### ISSUE TITLE
[BUG] Semantic Chunks are to Big

### ISSUE THREAD

**Issue by aribornstein** [chonkie-ai/chonkie#83] opened 2024-12-09 09:23 UTC
**Describe the bug**
Even though chunk size is set 512 semantic chunking is returning one big chunk for my text with 3263 tokens

**To Reproduce**
```python
from chonkie import SemanticChunker

# Basic initialization with default parameters
chunker = SemanticChunker(
    embedding_model="minishlab/potion-base-8M",  # Default model
    threshold=0.6,                   # Similarity threshold (0-1)
    chunk_size=512,                             # Maximum tokens per chunk
    # initial_sentences=1                         # Initial sentences per chunk
)

text = re.sub(r'[\r\n]+', ' ', text)
text = re.sub(r'[^A-Za-z0-9 ]+', '', text)
chunks = chunker.chunk(text)

for chunk in chunks:
    print(f"Chunk text: {chunk.text}")
    print(f"Token count: {chunk.token_count}")
    print(f"Number of sentences: {len(chunk.sentences)}")

-- Output

Token count: 3263
Number of sentences: 1
```

**Expected behavior**
I expect to have least 7 chunks for the input text clustered by semantic similarity 

**Screenshots**

**Additional context**

**Comment by bhavnicksm** [comment] 2024-12-09 13:20
Hey @aribornstein!

Thanks for opening the issue! 😊

I'll try to replicate the issue today. If you could pass me a colab notebook which replicates it, I would be able to create a fix for it sooner. If not, even a sample text piece to reproduce the issue would be helpful!

Will update on this asap! Thanks! ☺️

**Comment by bhavnicksm** [comment] 2024-12-12 17:17
Hey @aribornstein!

This example is very clever! 😂

I just noticed you removed all sentence markers, which means it treats the entire passage as a single sentence, and since we have `min_sentences` set to 1 by default, it would by-pass the `chunk_size` argument since `min_sentences` takes priority here.

If you have text without sentence delimiters like this, this would fail every SentenceChunker or SemanticChunker out there, I would suggest using `TokenChunker` or `WordChunker` as an alternative. 

Would love to hear if you have an alternate solution for this or feedback :)

Thanks! 😊

**Comment by bhavnicksm** [comment] 2024-12-16 16:45
Closing issue because it's expected behavior; please reopen the issue if there is any feedback or mods required.

Thanks! 😊

**Closed by bhavnicksm** 2024-12-16 16:45 UTC
Labels: bug

**Comment by aribornstein** [comment] 2024-12-22 12:11
This makes sense. I didn't realize that chonky relies on delimiters to segment text.  I would consider seeing if there is a way to use a light weight model to segment coherent text if the used doesn't provide sentences. Let me think about this as well.
